title: Presentations | Rebecca Lynn Cremona
description: >-
  Presentations by Rebecca Lynn Cremona
baseurl: "/presentations"
url: "https://rebeccacremona.github.io"
permalink: pretty

markdown: kramdown
kramdown:
  parse_block_html: true
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
